### PR TITLE
Upgrade to BND 3.0.0 and Tycho 0.23.1

### PR DESCRIPTION
**Pull request by lwr1**
Hi,

Updated the bnd and maven-bundle-plugin to latest version as a solution to:

https://github.com/reficio/p2-maven-plugin/issues/81

which is related to: https://issues.apache.org/jira/browse/FELIX-4005

Aside from the pom and imports, the only actual change has been done to the AquteBundler (the calcManifest() method from the bnd's Analyzer doesn't automatically set it on the Jar instance anymore). Also updated Tycho.

I admit I haven't tested it extensively but it does seem to solve the Java 8 problem in the project I'm currently using it with so I thought I'd share.

Cheers,
Łukasz

### CODE REVIEW

**Comment by Raccoonwao** [comment]
Hi, we encountered similar issue which failed to scan all import packages from classes.  Could someone kindly suggest a date to have the dependency upgraded?

**Comment by tombujok** [comment]
Thx

**Comment by tombujok** [comment]
@lwr1 I'm looking for contributors / commiters. Will you or your company be willing to invest some time in maintaining p2-maven-plugin? I'm running out of time and I do not use the plugin anymore (not in RCP project anymore)

**Comment by Raccoonwao** [comment]
Thanks @tombujok, any eta for the release time?  The lastest from Maven repo is still 1.1.1.

We are eagerly looking forward to having this fixed. :)

**Comment by tombujok** [comment]
Guys, would anyone rebase #75 against the current master and merge minor conflicts?
I would really appreciate it. Then I could release a new version.

**Comment by salsolatragus** [comment]
Any updates on this? I tried the rebase, but failed to resolve some of the conflicts (see https://github.com/reficio/p2-maven-plugin/pull/75#issuecomment-200781156)...

**Comment by cleanerx** [comment]
Hm. This has been lying around for some while. Any progress since then ?

**Comment by salsolatragus** [comment]
Nothing I'm aware of...

**Comment by tombujok** [comment]
Guys, it's just my lack of time.
Is anyone interested to join as a contributor?

**Comment by Raccoonwao** [comment]
I am happy to help

**Comment by LorenzoBettini** [comment]
Since this PR is merged, then https://github.com/reficio/p2-maven-plugin/issues/81 should be fixed, shouldn't it? I'm using the latest available 1.2.0-SNAPSHOT but I still experience this problem...

**Pull request merged**
