### PR TITLE
Merged "feature-generation" with current master 

### PR DESCRIPTION
**Pull request by sparsick**
- Original PR #75 
- solved merge conflicts
- update broken import package in IT
- update broken field / parameter type

### CODE REVIEW

**Comment by sparsick** [comment]
@tombujok Can you predict when you have time to review this PR? It would be very helpful for me. Thank you.

**Comment by tombujok** [comment]
That's an awesome job. Thx!

**Comment by sparsick** [comment]
Thank you for merging! Can you predict when you will release a new version?

**Comment by tombujok** [comment]
I hope that in the next 2-3 days. I'm still waiting on this one for a bit:
https://github.com/reficio/p2-maven-plugin/pull/116

If there's not resolution I'll release without it till Monday.

**Pull request merged**
