### PR TITLE
Fix #107

### LINKED ISSUE #107: Rename the config option "categoryFileURL" to "categoryFilePath"
First up, thanks for the great plug-in! It makes my life easier every week!

One little thing (which has just led to a build failure here), I think the configuration option `categoryFileURL` should be renamed to `categoryFilePath` (or similar), as the value isn't expected to be a URL (no protocol), but a path.

E.g., using a URL incl. protocol breaks the build:

1. Include `<categoryFileURL>file://${basedir}/category.xml</categoryFileURL>` in the POM.
2. Run `mvn p2:site`: build fails.

Using a path works like a charm:

1. Include `<categoryFileURL>${basedir}/category.xml</categoryFileURL>` in the POM.
2. Run `mvn p2:site`: build succeeds (if the file exists).

### PR DESCRIPTION
**Pull request by sdruskat**
I've change the name for the config option `categoryFileURL` to `categoryFilePath`, as the expected value is a path rather than a URL, i.e., has to be defined sans protocol.

Also included an integration test.

Many thanks for a great plugin!

### CODE REVIEW

**Comment by sdruskat** [comment]
Travis cannot find the custom category file at the moment. Working on it.

**Comment by tombujok** [comment]
Good job! The only problem is that we can't introduce changes that are not backward compatible.
We should keep the Url and generate a warning that this option is now called Path. Otherwise builds will break for people who are using the Url option.

**Comment by sdruskat** [comment]
@tombujok Agree, hadn't thought about that at all. I'll give you a heads up once I've managed to make Travis happy again and added the warning. Might be a few days though.

**Comment by tombujok** [comment]
@sdruskat any update on this?

**Pull request closed without merging**
